### ISSUE TITLE
Ошибка неверной контрольной суммы в микросервисе bandwidth-provider-node

### ISSUE THREAD

**Issue by sxiii** [GolosChain/golosio-launching#10]
Bandwidth-provider-node без конца рестартит (как и wallet-node). 

Смотрим в него: `docker logs --tail 100 -f bandwidth-provider-node`

<details><summary>Видим вот это:</summary>

```

at new JsSignatureProvider (/app/node_modules/cyberwayjs/dist/eosjs-jssig.js:66:81)
    at Object.<anonymous> (/app/src/controllers/BandwidthProvider.js:20:29)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/app/src/services/Connector.js:3:27)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/app/src/Main.js:5:19)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
/app/node_modules/cyberwayjs/dist/eosjs-jssig.js:76
            finally { if (e_1) throw e_1.error; }
                               ^

Error: Invalid checksum, 79f7f222 != cf948670
    at Object.checkDecode (/app/node_modules/eosjs-ecc/lib/key_utils.js:269:11)
    at parseKey (/app/node_modules/eosjs-ecc/lib/key_private.js:163:31)
    at Function.PrivateKey.fromString (/app/node_modules/eosjs-ecc/lib/key_private.js:271:10)
    at new JsSignatureProvider (/app/node_modules/cyberwayjs/dist/eosjs-jssig.js:66:81)
    at Object.<anonymous> (/app/src/controllers/BandwidthProvider.js:20:29)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/app/src/services/Connector.js:3:27)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/app/src/Main.js:5:19)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
/app/node_modules/cyberwayjs/dist/eosjs-jssig.js:76
            finally { if (e_1) throw e_1.error; }
                               ^

Error: Invalid checksum, 79f7f222 != cf948670
    at Object.checkDecode (/app/node_modules/eosjs-ecc/lib/key_utils.js:269:11)
    at parseKey (/app/node_modules/eosjs-ecc/lib/key_private.js:163:31)
    at Function.PrivateKey.fromString (/app/node_modules/eosjs-ecc/lib/key_private.js:271:10)
    at new JsSignatureProvider (/app/node_modules/cyberwayjs/dist/eosjs-jssig.js:66:81)
    at Object.<anonymous> (/app/src/controllers/BandwidthProvider.js:20:29)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/app/src/services/Connector.js:3:27)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/app/src/Main.js:5:19)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
/app/node_modules/cyberwayjs/dist/eosjs-jssig.js:76
            finally { if (e_1) throw e_1.error; }
                               ^

Error: Invalid checksum, 79f7f222 != cf948670
    at Object.checkDecode (/app/node_modules/eosjs-ecc/lib/key_utils.js:269:11)
    at parseKey (/app/node_modules/eosjs-ecc/lib/key_private.js:163:31)
    at Function.PrivateKey.fromString (/app/node_modules/eosjs-ecc/lib/key_private.js:271:10)
    at new JsSignatureProvider (/app/node_modules/cyberwayjs/dist/eosjs-jssig.js:66:81)
    at Object.<anonymous> (/app/src/controllers/BandwidthProvider.js:20:29)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/app/src/services/Connector.js:3:27)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/app/src/Main.js:5:19)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)

```
</details>

Значит ли эта и все прочие ошибки что ноды голоса и кибервея могут работать только в случае, если у нашего веб-сервера есть доменное имя и настроен SSL? Или есть какие-то другие пути?

**Comment by b1acksun** [comment]
Указан неправильный приватный ключ
