### ISSUE TITLE
Другие ошибки в трёх микросервисах

### ISSUE THREAD

**Issue by sxiii** [GolosChain/golosio-launching#11]
Объединил в одно сообщение - ибо аж три контейнера рестартят и в каждом свои ошибки. Итак:

<details><summary>Ошибки в prism-node (`docker logs --tail 100 prism-node`):</summary>

```
2020-10-25 19:46:41 <1> [error] BulkSaver failed: { BulkWriteError: E11000 duplicate key error collection: prism.profiles index: userId_1 dup key: { userId: "kjcr1ce14ztf" }
    at OrderedBulkOperation.handleWriteError (/usr/src/app/node_modules/mongoose/node_modules/mongodb/lib/bulk/common.js:1205:11)
    at resultHandler (/usr/src/app/node_modules/mongoose/node_modules/mongodb/lib/bulk/common.js:519:23)
    at /usr/src/app/node_modules/mongoose/node_modules/mongodb/lib/core/connection/pool.js:414:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
  index: 0,
  code: 11000,
  errmsg:
   'E11000 duplicate key error collection: prism.profiles index: userId_1 dup key: { userId: "kjcr1ce14ztf" }',
  op:
   { chargersRaw:
      { votes: [Object],
        posts: [Object],
        comments: [Object],
        postbw: [Object] },
     subscriptions:
      { userIds: [],
        usersCount: 0,
        communityIds: [],
        communitiesCount: 0 },
     subscribers:
      { userIds: [],
        usersCount: 0,
        communityIds: [],
        communitiesCount: 0 },
     stats: { reputation: 0, postsCount: 0, commentsCount: 0 },
     isGenesisUser: true,
     leaderIn: [],
     isGolosVestingOpened: true,
     _id: 5f95d6217230727bfca8fc77,
     userId: 'kjcr1ce14ztf',
     usernames: { gls: 'miners' },
     registration: { time: null },
     __v: 0,
     createdAt: 2020-10-25T19:46:41.578Z,
     updatedAt: 2020-10-25T19:46:41.578Z },
  name: 'BulkWriteError',
  driver: true,
  err:
   { index: 0,
     code: 11000,
     errmsg:
      'E11000 duplicate key error collection: prism.profiles index: userId_1 dup key: { userId: "kjcr1ce14ztf" }',
     op:
      { chargersRaw: [Object],
        subscriptions: [Object],
        subscribers: [Object],
        stats: [Object],
        isGenesisUser: true,
        leaderIn: [],
        isGolosVestingOpened: true,
        _id: 5f95d6217230727bfca8fc77,
        userId: 'kjcr1ce14ztf',
        usernames: [Object],
        registration: [Object],
        __v: 0,
        createdAt: 2020-10-25T19:46:41.578Z,
        updatedAt: 2020-10-25T19:46:41.578Z } },
  result:
   BulkWriteResult {
     result:
      { ok: 1,
        writeErrors: [Array],
        writeConcernErrors: [],
        insertedIds: [Array],
        nInserted: 0,
        nUpserted: 0,
        nMatched: 0,
        nModified: 0,
        nRemoved: 0,
        upserted: [] } },
  [Symbol(mongoErrorContextSymbol)]: {} }
```

</details>

<details><summary>Ошибки в wallet-node (`docker logs --tail 100 wallet-node`):</summary>
 
```
2020-10-25 19:46:41 <1> [error] BulkSaver failed: { BulkWriteError: E11000 duplicate key error collection: prism.profiles index: userId_1 dup key: { userId: "kjcr1ce14ztf" }
    at OrderedBulkOperation.handleWriteError (/usr/src/app/node_modules/mongoose/node_modules/mongodb/lib/bulk/common.js:1205:11)
    at resultHandler (/usr/src/app/node_modules/mongoose/node_modules/mongodb/lib/bulk/common.js:519:23)
    at /usr/src/app/node_modules/mongoose/node_modules/mongodb/lib/core/connection/pool.js:414:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
  index: 0,
  code: 11000,
  errmsg:
   'E11000 duplicate key error collection: prism.profiles index: userId_1 dup key: { userId: "kjcr1ce14ztf" }',
  op:
   { chargersRaw:
      { votes: [Object],
        posts: [Object],
        comments: [Object],
        postbw: [Object] },
     subscriptions:
      { userIds: [],
        usersCount: 0,
        communityIds: [],
        communitiesCount: 0 },
     subscribers:
      { userIds: [],
        usersCount: 0,
        communityIds: [],
        communitiesCount: 0 },
     stats: { reputation: 0, postsCount: 0, commentsCount: 0 },
     isGenesisUser: true,
     leaderIn: [],
     isGolosVestingOpened: true,
     _id: 5f95d6217230727bfca8fc77,
     userId: 'kjcr1ce14ztf',
     usernames: { gls: 'miners' },
     registration: { time: null },
     __v: 0,
     createdAt: 2020-10-25T19:46:41.578Z,
     updatedAt: 2020-10-25T19:46:41.578Z },
  name: 'BulkWriteError',
  driver: true,
  err:
   { index: 0,
     code: 11000,
     errmsg:
      'E11000 duplicate key error collection: prism.profiles index: userId_1 dup key: { userId: "kjcr1ce14ztf" }',
     op:
      { chargersRaw: [Object],
        subscriptions: [Object],
        subscribers: [Object],
        stats: [Object],
        isGenesisUser: true,
        leaderIn: [],
        isGolosVestingOpened: true,
        _id: 5f95d6217230727bfca8fc77,
        userId: 'kjcr1ce14ztf',
        usernames: [Object],
        registration: [Object],
        __v: 0,
        createdAt: 2020-10-25T19:46:41.578Z,
        updatedAt: 2020-10-25T19:46:41.578Z } },
  result:
   BulkWriteResult {
     result:
      { ok: 1,
        writeErrors: [Array],
        writeConcernErrors: [],
        insertedIds: [Array],
        nInserted: 0,
        nUpserted: 0,
        nMatched: 0,
        nModified: 0,
        nRemoved: 0,
        upserted: [] } },
  [Symbol(mongoErrorContextSymbol)]: {} }
root@Popov:~/golosio-launching# docker logs --tail 100 wallet-node
2020-10-25 19:48:35 <1> [info] GLS_LOCAL_METRICS = false
2020-10-25 19:48:35 <1> [info] GLS_PRESERVE_LOCAL_METRICS = false
2020-10-25 19:48:35 <1> [info] GLS_WAIT_FOR_TRANSACTION_TIMEOUT = 300000
2020-10-25 19:48:35 <1> [info] GLS_CYBERWAY_CONNECT = undefined
2020-10-25 19:48:35 <1> [info] GLS_RECENT_BLOCKS_TIME_DELTA = 300000
2020-10-25 19:48:35 <1> [info] GLS_SAVE_GENESIS_EXAMPLES = false
2020-10-25 19:48:35 <1> [info] GLS_NATS_MAX_IN_FLIGHT = 10
2020-10-25 19:48:35 <1> [info] GLS_SKIP_MISSING_TRANSACTIONS = false
2020-10-25 19:48:35 <1> [info] GLS_DB_LOGS_ENABLED = false
2020-10-25 19:48:35 <1> [info] ---
2020-10-25 19:48:35 <1> [info] Service config params:
2020-10-25 19:48:35 <1> [info] ---
2020-10-25 19:48:35 <1> [info] NODE_OPTIONS = undefined
2020-10-25 19:48:35 <1> [info] GLS_MAX_FEED_LIMIT = 100
2020-10-25 19:48:35 <1> [info] GLS_DELEGATION_ROUND_LENGTH = 21
2020-10-25 19:48:35 <1> [info] GLS_REVERT_TRACE_CLEANER_INTERVAL = 300000
2020-10-25 19:48:35 <1> [info] GLS_CONTENT_PREVIEW_LENGTH = 200
2020-10-25 19:48:35 <1> [info] GLS_PRISM_CONNECT = undefined
2020-10-25 19:48:35 <1> [info] GLS_LOGS_ON = false
2020-10-25 19:48:35 <1> [info] GLS_SKIP_GENESIS = false
2020-10-25 19:48:35 <1> [info] GLS_WITHDRAW_INTERWALS = 13
2020-10-25 19:48:35 <1> [info] GLS_WITHDRAW_INTERWALS_SECONDS = 604800
2020-10-25 19:48:35 <1> [info] GLS_CYBERWAY_HTTP_URL = http://46.148.232.188:8888
2020-10-25 19:48:35 <1> [info] GLS_VERBOSE_LOGS = true
2020-10-25 19:48:35 <1> [info] ---
2020-10-25 19:48:35 <1> [info] Start MongoDB...
2020-10-25 19:48:35 <1> [info] MongoDB connection established.
(node:1) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
2020-10-25 19:48:35 <1> [info] The MongoDB done!
2020-10-25 19:48:35 <1> [info] Start services...
2020-10-25 19:48:35 <1> [info] Start RpcActualizer...
2020-10-25 19:48:35 <1> [info] The RpcActualizer done!
2020-10-25 19:48:35 <1> [info] Start Prism...
2020-10-25 19:48:35 <1> [info] The Prism done!
2020-10-25 19:48:35 <1> [info] Start Connector...
2020-10-25 19:48:35 <1> [info] The Connector done!
2020-10-25 19:48:35 <1> [info] Start services done!
2020-10-25 19:48:35 <1> [info] Main service started!
2020-10-25 19:48:36 <1> [log] Blockchain block subscriber connected.
2020-10-25 19:48:36 <1> [info] Subscribe on blocks, seq: 1
2020-10-25 19:48:36 <1> [error] Received sequence doesn't match to subscribe sequence, subscribe: 1, received: 66884080
2020-10-25 19:49:38 <1> [info] ENV-based config:
2020-10-25 19:49:38 <1> [info] Core config params:
2020-10-25 19:49:38 <1> [info] ---
2020-10-25 19:49:38 <1> [info] GLS_MONGO_CONNECT = mongodb://wallet-mongo/wallet
2020-10-25 19:49:38 <1> [info] GLS_DAY_START = 3
2020-10-25 19:49:38 <1> [info] GLS_METRICS_HOST = 127.0.0.1
2020-10-25 19:49:38 <1> [info] GLS_METRICS_PORT = 9777
2020-10-25 19:49:38 <1> [info] GLS_CONNECTOR_HOST = 0.0.0.0
2020-10-25 19:49:38 <1> [info] GLS_CONNECTOR_PORT = 3040
2020-10-25 19:49:38 <1> [info] GLS_BLOCKCHAIN_BROADCASTER_SERVER_NAME = cyberway
2020-10-25 19:49:38 <1> [info] GLS_BLOCKCHAIN_BROADCASTER_CLIENT_NAME = wallet-1
2020-10-25 19:49:38 <1> [info] GLS_BLOCKCHAIN_BROADCASTER_CONNECT = nats://rkGZ6Kvf:W2OrKBlz6h5J6ITfaC3EfwCCyBQXgJbM@46.148.232.188:4222
2020-10-25 19:49:38 <1> [info] GLS_BLOCK_SUBSCRIBER_REPLAY_TIME_DELTA = 600000
2020-10-25 19:49:38 <1> [info] GLS_BLOCK_SUBSCRIBER_CLEANER_INTERVAL = 600000
2020-10-25 19:49:38 <1> [info] GLS_BLOCK_SUBSCRIBER_LAST_BLOCK_STORE = 1000
2020-10-25 19:49:38 <1> [info] GLS_EXTERNAL_CALLS_METRICS = false
2020-10-25 19:49:38 <1> [info] GLS_SYSTEM_METRICS = false
2020-10-25 19:49:38 <1> [info] GLS_USE_ONLY_RECENT_BLOCKS = false
2020-10-25 19:49:38 <1> [info] GLS_LOCAL_METRICS = false
2020-10-25 19:49:38 <1> [info] GLS_PRESERVE_LOCAL_METRICS = false
2020-10-25 19:49:38 <1> [info] GLS_WAIT_FOR_TRANSACTION_TIMEOUT = 300000
2020-10-25 19:49:38 <1> [info] GLS_CYBERWAY_CONNECT = undefined
2020-10-25 19:49:38 <1> [info] GLS_RECENT_BLOCKS_TIME_DELTA = 300000
2020-10-25 19:49:38 <1> [info] GLS_SAVE_GENESIS_EXAMPLES = false
2020-10-25 19:49:38 <1> [info] GLS_NATS_MAX_IN_FLIGHT = 10
2020-10-25 19:49:38 <1> [info] GLS_SKIP_MISSING_TRANSACTIONS = false
2020-10-25 19:49:38 <1> [info] GLS_DB_LOGS_ENABLED = false
2020-10-25 19:49:38 <1> [info] ---
2020-10-25 19:49:38 <1> [info] Service config params:
2020-10-25 19:49:38 <1> [info] ---
2020-10-25 19:49:38 <1> [info] NODE_OPTIONS = undefined
2020-10-25 19:49:38 <1> [info] GLS_MAX_FEED_LIMIT = 100
2020-10-25 19:49:38 <1> [info] GLS_DELEGATION_ROUND_LENGTH = 21
2020-10-25 19:49:38 <1> [info] GLS_REVERT_TRACE_CLEANER_INTERVAL = 300000
2020-10-25 19:49:38 <1> [info] GLS_CONTENT_PREVIEW_LENGTH = 200
2020-10-25 19:49:38 <1> [info] GLS_PRISM_CONNECT = undefined
2020-10-25 19:49:38 <1> [info] GLS_LOGS_ON = false
2020-10-25 19:49:38 <1> [info] GLS_SKIP_GENESIS = false
2020-10-25 19:49:38 <1> [info] GLS_WITHDRAW_INTERWALS = 13
2020-10-25 19:49:38 <1> [info] GLS_WITHDRAW_INTERWALS_SECONDS = 604800
2020-10-25 19:49:38 <1> [info] GLS_CYBERWAY_HTTP_URL = http://46.148.232.188:8888
2020-10-25 19:49:38 <1> [info] GLS_VERBOSE_LOGS = true
2020-10-25 19:49:38 <1> [info] ---
2020-10-25 19:49:38 <1> [info] Start MongoDB...
2020-10-25 19:49:38 <1> [info] MongoDB connection established.
(node:1) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
2020-10-25 19:49:38 <1> [info] The MongoDB done!
2020-10-25 19:49:38 <1> [info] Start services...
2020-10-25 19:49:38 <1> [info] Start RpcActualizer...
2020-10-25 19:49:38 <1> [info] The RpcActualizer done!
2020-10-25 19:49:38 <1> [info] Start Prism...
2020-10-25 19:49:38 <1> [info] The Prism done!
2020-10-25 19:49:38 <1> [info] Start Connector...
2020-10-25 19:49:38 <1> [info] The Connector done!
2020-10-25 19:49:38 <1> [info] Start services done!
2020-10-25 19:49:38 <1> [info] Main service started!
2020-10-25 19:49:39 <1> [log] Blockchain block subscriber connected.
2020-10-25 19:49:39 <1> [info] Subscribe on blocks, seq: 1
2020-10-25 19:49:39 <1> [error] Received sequence doesn't match to subscribe sequence, subscribe: 1, received: 66884182
```

</details>

<details><summary>Ошибки в bandwidth-provider-node (`docker logs --tail 100 bandwidth-provider-node`):</summary>
Ошибка сверки контрольных сумм - Те же самые, что в issue #10 
</details>

**Comment by b1acksun** [comment]
Ошибки в prism-node и wallet-node свидетельствуют о том, что контейнер был перезагружен во время парсинга генезиса, необходимо перезапустить c удалением volume `sudo docker-compose down -v && sudo docker-compose up -d --build`

Ошибка bandwidth-provider-node - указан неправильный приватный ключ
