### ISSUE TITLE
Третий шаг (Запуск клиента golos.io) не работает

### ISSUE THREAD

**Issue by sxiii** [GolosChain/golosio-launching#7]
У нас нету домена и нету HTTPS сертификата (на данном этапе, пока тестирование). 
По этой причине, очевидно, я использую везде HTTP вместо HTTPS.

На первом сервере поднята ТОЛЬКО нода cyberway (первый набор контейнеров и реп из этой инструкции)

На втором сервере подняты микросервисы и golosio (второй и третий набор контейнеров из этой инструкции)

В рамках golosio делаю в .env:
FACADE_CONNECT=http://facade-node:3001
Т.е. пытаюсь использовать нейминг докер-контейнера,

<details><summary>Не работает с ошибкой "адрес не найден":</summary>

```
golos  | yarn run v1.22.10
golos  | $ NODE_ENV=production node server/server.js
golos  | > Ready on http://localhost:3000
golos  | { Error: getaddrinfo ENOTFOUND facade-node facade-node:3001
golos  |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:58:26)
golos  |   errno: 'ENOTFOUND',
golos  |   code: 'ENOTFOUND',
golos  |   syscall: 'getaddrinfo',
golos  |   hostname: 'facade-node',
golos  |   host: 'facade-node',
```

</details>

В рамках golosio делаю в .env:
FACADE_CONNECT=http://127.0.0.1:3001
Т.е. использую local loopback,

<details><summary>Не работает с ошибкой "подключение отклонено":</summary>

```
golos  | { Error: connect ECONNREFUSED 127.0.0.1:3001
golos  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1088:14)
golos  |   errno: 'ECONNREFUSED',
golos  |   code: 'ECONNREFUSED',
golos  |   syscall: 'connect',
golos  |   address: '127.0.0.1',
golos  |   port: 3001 }
```
</details>

ЧЯДНТ (Что я делаю не так)?

**Comment by Kwaskoff** [comment]
пробуй ввести внешний адрес сервера или localhost

**Comment by sxiii** [comment]
Да, внешний адрес сервера вроде бы сработал: http://46.148.231.204:3000

Оставлю этот issue чтобы команда могла добавить информацию о том что подходит только *внешний публичный адрес* или *доменное имя* - это важно, в документацию. Как добавят - закрою
