### ISSUE TITLE
Ошибка получения вестинг-баланса аккаунта

### ISSUE THREAD

**Issue by sxiii** [GolosChain/golosio-launching#8]
О чём она говорит?

<details><summary>Вот сама ошибка:</summary>

```
golos  | yarn run v1.22.10
golos  | $ NODE_ENV=production node server/server.js
golos  | > Ready on http://localhost:3000
golos  | { GateError: GateError wallet.getVestingSupplyAndBalance: Internal error
golos  |     at client.request (/app/src/.next/server/static/sz_zki82AeRjXKcVFbC3z/pages/feed.js:1804:18)
golos  |     at ClientHttp.Client._parseResponse (/app/node_modules/jayson/lib/client/index.js:207:10)
golos  |     at /app/node_modules/jayson/lib/client/index.js:138:10
golos  |     at Object.Utils.JSON.parse (/app/node_modules/jayson/lib/utils.js:254:3)
golos  |     at IncomingMessage.<anonymous> (/app/node_modules/jayson/lib/client/http.js:82:22)
golos  |     at IncomingMessage.emit (events.js:198:15)
golos  |     at IncomingMessage.EventEmitter.emit (domain.js:504:23)
golos  |     at endReadableNT (_stream_readable.js:1139:12)
golos  |     at processTicksAndRejections (internal/process/task_queues.js:81:17)
golos  |   message:
golos  |    'GateError wallet.getVestingSupplyAndBalance: Internal error',
golos  |   originalMessage: 'Internal error',
golos  |   code: -32603,
golos  |   method: 'wallet.getVestingSupplyAndBalance' }
```

</details>

Значит ли это, что я неверно указал ключи или имена аккаунтов в "GLS_PROVIDER_PUBLIC_KEY, GLS_PROVIDER_WIF, GLS_PROVIDER_USERNAME" или что-то ещё?

**Comment by b1acksun** [comment]
Скорее всего ошибка связанна с тем, что wallet-node запустился с ошибкой
