### ISSUE TITLE
RPCActualizer tick failed (ошибка подключения как по HTTP, так и по HTTPS для контейнера wallet-node из microservices)

### ISSUE THREAD

**Issue by sxiii** [GolosChain/golosio-launching#9]
Контейнер wallet-node постоянно рестартит. Делаю `docker logs --tail 100 -f wallet-node`, получается

<details><summary>Ошибка:</summary>

```

2020-10-25 18:59:48 <1> [error] RpcActualizer tick failed: { FetchError: request to http://46.148.232.188/v1/chain/get_producer_schedule failed, reason: connect ECONNREFUSED 46.148.232.188:80
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  message:
   'request to http://46.148.232.188/v1/chain/get_producer_schedule failed, reason: connect ECONNREFUSED 46.148.232.188:80',
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED' }
```

</details>

В настройках .env пробовал указывать как CYBERWAY_HTTP_URL=http://ip так и CYBERWAY_HTTP_URL=https://ip, не работает в обоих вариантах, ошибка та же, что указана тут

**Comment by b1acksun** [comment]
Необходимо указать порт `CYBERWAY_HTTP_URL=http://ip:port` -> `http://46.148.232.188:8888`

**Comment by sxiii** [comment]
@b1acksun да, сделал так ещё вчера, старая ошибка ушла, но теперь новая:
```
2020-10-26 08:59:05 <1> [error] Received sequence doesn't match to subscribe sequence, subscribe: 1, received: 66982806
```
